#pring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.waziynckmiulgscryxpo&password=[YOUR-PASSWORD]
# spring.datasource.username=postgres
# spring.datasource.password=YOUR_PASSWORD

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Server Configuration
# =========================
server.port=8080

# =========================
# Supabase PostgreSQL Database
# =========================
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.waziynckmiulgscryxpo
spring.datasource.password=BX5aDseKsb0EkS0H
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Hibernate / JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT Configuration
# =========================
jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlQmFzZTY0S2V5Rm9ySldUQXV0aGVudGljYXRpb25BbmRVUElTaW11bGF0b3IyMDI2
jwt.expiration=86400000
# =========================
# Logging (Optional)
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG